name: Alleleauto
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - perl
  - r-base=4.2
  - r-essentials
  - blast
  - biopython
  - bedtools
  - wgdi
  - ParaFly  
  - bioconductor-deseq2 
  - pip
  - pip:
    - jcvi
